# 数据库配置
database:
  host: localhost
  port: 54321
  user: system
  password: 123456
  dbname: demo
  schema_name: public


# 任务配置
tasks:
  # 设备导入任务
  equipment:
    title: 设备导入任务
    # 是否激活
    active: false
    # excel文件
    excel_file: /home/gaojunxin/demo1.xlsx
    # 设备基础信息表
    base_table: talble_name
    # 扩展信息表
    extend_table: ext_talbe_name
    # 用到的所有字典表
    dict_tables:
      # 设备类型字典
      - name: dict_table_name
        id_field: id
        name_field: name
    # 默认字段
    default_column:
      - name: id
      - name: create_by
        value: 1
      - name: update_by
        value: 1
      - name: status
        value: '0'
      - name: xxx
        value: "sheet_name"
    # 设备基础信息列
    base_column:
      # 分公司名称
      - name: eqled_term_bo_name
        index: 0
      # 作业公司名称
      - name: eqled_term_oper_name
        index: 1
      # 油(气)田名称
      - name: eqled_term_ogf_name
        index: 2
      # 设备编码
      - name: eqled_term_code
        index: 3
    # 编号列
    fk_id_column:
      # 分公司编号
      - name: demo_fk_table
        name_field: name1
        dict_table: talbe1
        value_prefix: "有限"
    # 扩展信息列
    ext_column:
      # 设备编号
      - name: eqled_id
        value: id
      # 设备名称
      - name: eqled_name
        value: eqled_term_name
      # 字段名称
      - name: field_name
        value: name
      # 字段值
      - name: field_value
        value: value
      # 是否基础字段
      - name: basic_field
        value: 0
