# 数据库配置
database:
  demo:
    host: 192.168.1.1
    port: 54321
    user: system
    password: 123456
    dbname: demo
    schema_name: public
  standard:
    host: 192.168.100.12
    port: 54321
    user: system
    password: 123456
    dbname: demo
    schema_name: public

# 日志配置
logging:
  level: info
  file: main.log
  max_size: 10MB
  backup_count: 5

# 用到的所有字典表
dict_tables:
  # 设备类型字典
  - name: epfaclas_term
    id_field: id
    name_field: name
    # 所在数据库
    db: demo
  # 组织字典
  - name: com_organization
    id_field: org_id
    name_field: org_short_name
    # 所在数据库
    db: demo
 
    